branches:
- main
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
# remove the comment from one of them according to your needs
- "@semantic-release/github"
# - "@semantic-release/gitlab"