branches:
- main
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
# remove the comment from one of them according to your needs
- "@semantic-release/github"
# - "@semantic-release/gitlab"